### ISSUE TITLE
`No existing credentials found. Please run `vercel login` or pass "--token" ` error when executing the command

### ISSUE THREAD

**Issue by chandan-zaag** [IamLizu/verceler#4]

**Comment by IamLizu** [comment]
Good find, we need to pass the vercel token which we already have from the user passed argument. And use that token to link the project in vercel.

A good place to start is this, https://github.com/IamLizu/verceler/blob/2218f966ee171d209e762e951bc0c6f13b09b3e5/src/utils/VercelManager.js#L21
